# Generated by Django 6.0.6 on 2026-06-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.CharField(choices=[('clothing', 'Clothing'), ('trousers', 'Trousers'), ('shoes', 'Shoes')], max_length=20)),
                ('value', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=20)),
            ],
        ),
    ]
