# Generated by Django 6.0.6 on 2026-06-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_sizeoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
