# Generated by Django 6.0.6 on 2026-06-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_item_created_by_item_given_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='given_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
