# Generated by Django 6.0.6 on 2026-06-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_route_reservation_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='auto_extended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='miss_reason',
            field=models.CharField(blank=True, choices=[('lapsed', 'Lapsed'), ('no_replacement', 'No replacement found')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='missed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('packed', 'Packed'), ('given', 'Given')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('packed', 'Packed'), ('given', 'Given'), ('missed', 'Missed')], default='reserved', max_length=20),
        ),
    ]
