# Generated by Django 6.0.6 on 2026-06-17 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reserve', 'Reserved item'), ('edit_reservation', 'Edited reservation'), ('cancel_reservation', 'Cancelled reservation'), ('collect', 'Collected item'), ('reassign', 'Re-assigned item'), ('new_sr', 'New special request'), ('confirm_sr', 'Confirmed special request'), ('cancel_sr', 'Cancelled special request')], max_length=20)),
                ('item_code', models.CharField(blank=True, max_length=20)),
                ('person', models.CharField(blank=True, max_length=100)),
                ('route_name', models.CharField(blank=True, max_length=100)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
